// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddmessageindiscussionforumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addmessageindiscussionforum() {
    // Test name: Add message in discussion forum
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/homepage | 
    driver.get("http://localhost:3000/homepage");
    // 2 | setWindowSize | 1228x824 | 
    driver.manage().window().setSize(new Dimension(1228, 824));
    // 3 | click | css=.dropdown-toggle | 
    driver.findElement(By.cssSelector(".dropdown-toggle")).click();
    // 4 | click | linkText=Student Login | 
    driver.findElement(By.linkText("Student Login")).click();
    // 5 | click | name=email | 
    driver.findElement(By.name("email")).click();
    // 6 | type | name=email | jahnvi.verma1220@gmail.com
    driver.findElement(By.name("email")).sendKeys("jahnvi.verma1220@gmail.com");
    // 7 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 8 | type | name=password | 169773@Jv
    driver.findElement(By.name("password")).sendKeys("169773@Jv");
    // 9 | sendKeys | name=password | ${KEY_ENTER}
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    // 10 | mouseOver | css=.studentlogin_btn__VnjUF | 
    {
      WebElement element = driver.findElement(By.cssSelector(".studentlogin_btn__VnjUF"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | click | css=.studentlogin_btn__VnjUF | 
    driver.findElement(By.cssSelector(".studentlogin_btn__VnjUF")).click();
    // 12 | click | css=li:nth-child(3) > .page-scroll | 
    driver.findElement(By.cssSelector("li:nth-child(3) > .page-scroll")).click();
    // 13 | click | linkText=View Course | 
    driver.findElement(By.linkText("View Course")).click();
    // 14 | runScript | window.scrollTo(0,192) | 
    js.executeScript("window.scrollTo(0,192)");
    // 15 | click | id=simple-tab-2 | 
    driver.findElement(By.id("simple-tab-2")).click();
    // 16 | click | css=.comment-form-textarea | 
    driver.findElement(By.cssSelector(".comment-form-textarea")).click();
    // 17 | type | css=.comment-form-textarea | Very educational
    driver.findElement(By.cssSelector(".comment-form-textarea")).sendKeys("Very educational");
    // 18 | click | css=.comment-form-button | 
    driver.findElement(By.cssSelector(".comment-form-button")).click();
    // 19 | click | css=li:nth-child(5) > .page-scroll | 
    driver.findElement(By.cssSelector("li:nth-child(5) > .page-scroll")).click();
    // 20 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 21 | close |  | 
    driver.close();
  }
}
