// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddSectioninCourseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addSectioninCourse() {
    // Test name: Add Section in Course
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/homepage | 
    driver.get("http://localhost:3000/homepage");
    // 2 | setWindowSize | 1228x824 | 
    driver.manage().window().setSize(new Dimension(1228, 824));
    // 3 | click | css=.dropdown-toggle | 
    driver.findElement(By.cssSelector(".dropdown-toggle")).click();
    // 4 | click | linkText=Educator Login | 
    driver.findElement(By.linkText("Educator Login")).click();
    // 5 | click | css=li:nth-child(2) > .page-scroll | 
    driver.findElement(By.cssSelector("li:nth-child(2) > .page-scroll")).click();
    // 6 | click | linkText=View Course | 
    driver.findElement(By.linkText("View Course")).click();
    // 7 | mouseOver | css=.MuiTypography-root > .MuiButtonBase-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiTypography-root > .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | click | css=.MuiTypography-root > .MuiButtonBase-root | 
    driver.findElement(By.cssSelector(".MuiTypography-root > .MuiButtonBase-root")).click();
    // 9 | mouseOut | css=.MuiTypography-root > .MuiButtonBase-root | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | id=outlined-basic | 
    driver.findElement(By.id("outlined-basic")).click();
    // 11 | mouseOver | css=.MuiButton-contained:nth-child(1) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | type | id=outlined-basic | Application Layer
    driver.findElement(By.id("outlined-basic")).sendKeys("Application Layer");
    // 13 | click | css=.MuiButton-contained:nth-child(1) | 
    driver.findElement(By.cssSelector(".MuiButton-contained:nth-child(1)")).click();
    // 14 | click | css=.MuiPaper-root:nth-child(2) .MuiTypography-root | 
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(2) .MuiTypography-root")).click();
    // 15 | mouseOver | css=.MuiPaper-root:nth-child(2) > .MuiCollapse-root .MuiButtonBase-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(2) > .MuiCollapse-root .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 16 | click | css=.MuiPaper-root:nth-child(2) > .MuiCollapse-root .MuiButtonBase-root | 
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(2) > .MuiCollapse-root .MuiButtonBase-root")).click();
    // 17 | mouseOut | css=.MuiPaper-root:nth-child(2) > .MuiCollapse-root .MuiButtonBase-root | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 18 | click | id=outlined-basic | 
    driver.findElement(By.id("outlined-basic")).click();
    // 19 | type | id=outlined-basic | test1
    driver.findElement(By.id("outlined-basic")).sendKeys("test1");
    // 20 | click | name=body | 
    driver.findElement(By.name("body")).click();
    // 21 | mouseOver | css=.MuiButton-containedPrimary:nth-child(1) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedPrimary:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 22 | type | name=body | test1_01
    driver.findElement(By.name("body")).sendKeys("test1_01");
    // 23 | click | css=.MuiButton-containedPrimary:nth-child(1) | 
    driver.findElement(By.cssSelector(".MuiButton-containedPrimary:nth-child(1)")).click();
    // 24 | mouseOut | css=.MuiButton-containedPrimary:nth-child(1) | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 25 | selectFrame | index=0 | 
    driver.switchTo().frame(0);
    // 26 | click | css=button | 
    driver.findElement(By.cssSelector("button")).click();
    // 27 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 28 | click | name=body | 
    driver.findElement(By.name("body")).click();
    // 29 | type | name=body | test101
    driver.findElement(By.name("body")).sendKeys("test101");
    // 30 | click | css=.MuiButton-containedPrimary:nth-child(1) | 
    driver.findElement(By.cssSelector(".MuiButton-containedPrimary:nth-child(1)")).click();
    // 31 | selectFrame | index=0 | 
    driver.switchTo().frame(0);
    // 32 | click | css=button | 
    driver.findElement(By.cssSelector("button")).click();
    // 33 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 34 | click | css=.MuiButton-text | 
    driver.findElement(By.cssSelector(".MuiButton-text")).click();
    // 35 | close |  | 
    driver.close();
  }
}
