// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignUpRegisterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signUpRegister() {
    // Test name: Sign Up / Register
    // Step # | name | target | value
    // 1 | open | /homepage | 
    driver.get("http://localhost:3000/homepage/homepage");
    // 2 | setWindowSize | 1552x840 | 
    driver.manage().window().setSize(new Dimension(1552, 840));
    // 3 | click | css=.dropdown-toggle | 
    driver.findElement(By.cssSelector(".dropdown-toggle")).click();
    // 4 | click | linkText=Student Login | 
    driver.findElement(By.linkText("Student Login")).click();
    // 5 | click | linkText=Sign up | 
    driver.findElement(By.linkText("Sign up")).click();
    // 6 | click | name=fname | 
    driver.findElement(By.name("fname")).click();
    // 7 | type | name=fname | Jahnvi
    driver.findElement(By.name("fname")).sendKeys("Jahnvi");
    // 8 | click | name=lname | 
    driver.findElement(By.name("lname")).click();
    // 9 | type | name=lname | Verma
    driver.findElement(By.name("lname")).sendKeys("Verma");
    // 10 | click | name=email | 
    driver.findElement(By.name("email")).click();
    // 11 | type | name=email | jahnvi.verma1220@gmail.com
    driver.findElement(By.name("email")).sendKeys("jahnvi.verma1220@gmail.com");
    // 12 | click | name=phone | 
    driver.findElement(By.name("phone")).click();
    // 13 | type | name=phone | 9016493012
    driver.findElement(By.name("phone")).sendKeys("9016493012");
    // 14 | click | name=dob | 
    driver.findElement(By.name("dob")).click();
    // 15 | click | name=dob | 
    driver.findElement(By.name("dob")).click();
    // 16 | type | name=dob | 2003-09-20
    driver.findElement(By.name("dob")).sendKeys("2003-09-20");
    // 17 | click | id=educationLevel | 
    driver.findElement(By.id("educationLevel")).click();
    // 18 | select | id=educationLevel | label=High School
    {
      WebElement dropdown = driver.findElement(By.id("educationLevel"));
      dropdown.findElement(By.xpath("//option[. = 'High School']")).click();
    }
    // 19 | click | id=country | 
    driver.findElement(By.id("country")).click();
    // 20 | select | id=country | label=India
    {
      WebElement dropdown = driver.findElement(By.id("country"));
      dropdown.findElement(By.xpath("//option[. = 'India']")).click();
    }
    // 21 | click | css=.gender1:nth-child(3) > label | 
    driver.findElement(By.cssSelector(".gender1:nth-child(3) > label")).click();
    // 22 | click | name=username | 
    driver.findElement(By.name("username")).click();
    // 23 | type | name=username | v_jahnvi
    driver.findElement(By.name("username")).sendKeys("v_jahnvi");
    // 24 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 25 | type | name=password | testp@assw0rd
    driver.findElement(By.name("password")).sendKeys("testp@assw0rd");
    // 26 | click | css=.studentlogin_showpass__cHT4n | 
    driver.findElement(By.cssSelector(".studentlogin_showpass__cHT4n")).click();
    // 27 | click | css=.studentlogin_showpass__cHT4n | 
    driver.findElement(By.cssSelector(".studentlogin_showpass__cHT4n")).click();
    // 28 | click | css=.studentlogin_btn__DxLYW | 
    driver.findElement(By.cssSelector(".studentlogin_btn__DxLYW")).click();
    // 29 | close |  | 
    driver.close();
  }
}
